{{- if .Values.serviceAccount.create -}}
{{- range $component := list "api" "evaluator" "web" "postgres" "redis" "nats" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flagforge.componentName" (dict "root" $ "component" $component) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "flagforge.componentLabels" (dict "root" $ "component" $component) | nindent 4 }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $.Values.serviceAccount.automount }}
{{- end }}
{{- if .Values.monitoring.standalone.enabled }}
{{- range $component := list "prometheus" "grafana" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flagforge.componentName" (dict "root" $ "component" $component) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "flagforge.componentLabels" (dict "root" $ "component" $component) | nindent 4 }}
automountServiceAccountToken: {{ $.Values.serviceAccount.automount }}
{{- end }}
{{- end }}
{{- end }}
